---
webservers:
  hosts:
    192.168.0.69 
    192.168.0.19
  vars:
    ansible_ssh_user: opstree
    ansible_user: web
appservers:
  hosts:
    192.168.0.69
    192.168.0.19 
  vars:
    ansible_ssh_private_key_file: /home/app/app.pem
    ansible_ssh_user: opstree
    ansible_user: app
dbservers:
  hosts:
    192.168.0.60
  vars:
    ansible_ssh_private_key_file: /home/db/db.pem
    ansible_ssh_user: opstree
    ansible_user: db
    ansible_port: 2022
zoneA:
  children:
    webservers:
    appservers:
    dbservers:
zoneB:
  children:
    webservers:
    appservers:
    dbservers:






