---
- hosts: localhost
  tasks:
  - name: Check file
    stat:
      path: /var/www/html/index.nginx-debian.html
    register: stat_result

  - name: Nginx install
    apt:
      name: nginx
      state: present
    when: stat_result.stat.exists == False
