---
- hosts: localhost
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present
  - name: Start Nginx
    service:
      name: nginx
      state: started
  - name: Stop Service
    service:
      name: nginx
      state: stopped
  - name: Fetch files
    copy:
      dest: /var/www/html/index.html
      content: "{{ ansible_hostname }} {{ ansible_system }} {{ ansible_interfaces }} {{ ansible_mounts }} {{ ansible_default_ipv4 }}"
  - name: Service Restart
    service:
       name: nginx
       state: restarted
