---

- hosts: localhost
  tasks:
   - debug:
       msg: "{{ item }}"
     with_items:
      - "{{ ansible_hostname }}"     
      - "{{ ansible_system }}"
      - "{{ ansible_interfaces }}"
      - "{{ ansible_mounts }}"
      - "{{ ansible_default_ipv4 }}"
