---
# tasks file for nginxrole
    - name: checking os
      when: ansible_distribution != "Ubuntu"
      debug:
        msg: "OS not supported"

    - name: install_nginx
      apt:
         name: nginx
         state: present
      notify:
        - restarting_nginx
      
    - name: hosting_custom_page
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: copying
      template:
              src: default.j2
              dest: /etc/nginx/sites-enabled/default
      notify:
        - restarting_nginx
   
