--- 
- name: install multiple packages 
  hosts: webservers
  become: true
  tasks: 
    - name: Installing Packages  
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
      - vim
      - nginx
      - apache2
      
  
   