--- 
- name: Create and manage Users
  hosts: webservers
  become: yes
  tasks: 
  - name: Create user
    user: 
      name: testuser
      state: present
  
  - name: Create group
    group:
      name: test
      state: present
  
  - name: user home directory and shell
    user: 
      name: testuser
      home: /home/testuser
      shell: /bin/bash
      group: test
   