---
- hosts: webserver1
  become: true
  vars_prompt:
  
  - name: user
    prompt: "Enter user name"
    private: no
  
  - name: shell
    prompt: "Enter shell"
    private: no
    
  tasks:
  - name: installing apache
    apt: name=apache2 state=latest

  - name: custom_homepage
    template:
       src: index.html
       dest: /var/www/html/index.html
  - name: install packages
    apt: 
        name: "{{ item }}"
        state: present
    with_items:
          - vim
          - ntp
          - git 
  - name: adding_user
    user:
         name: "{{ user }}"
         shell: "{{ shell }}"
  - name: adding user
    user:
       name: "{{ item }}"
       state: present
    with_items:
       - ninja
       - sensei
       - pankaj
       - dev
       - saumya
       - raushan
  - name: adding groups
    group:
        name: "{{ item }}"
        state: present
    with_items:
       - opstree
       - devops
  - name: adding_user_into_groups
    user:
         name: ninja
         group: opstree
    notify:
         -  restart_apache
  handlers:
     - name: restart_apache
       service:
           name: apache2
           state: restarted
