---
- hosts: webserver1
  become: true
  tasks:
    - name: creating_user
      user: 
          name: tom
      tags: user  

    - name: creating_group
      group:
           name: cat
      tags: group
