---
- hosts: webserver1
  become: true
  vars_prompt:
    
    - name: install      
      prompt: "Do you want to install cron. yep/nope"
      private: no
      
  tasks:

    - name: creating_user
      user: 
          name: tom
      tags: user  

    - name: creating_group
      group:
           name: cat
      tags: group
    
    - name: installing_cron
      apt:
          name: cron
          state: present
      when: install == 'yep'
      tags: cron
