---
- hosts: webserver1
  become: true
  vars_prompt:
    - name: username
      prompt: "Enter your username"
      private: no
      default: Opstree
    - name: port
      prompt: "Enter your port number"
      private: no
      default: 80
  roles:
    - role: nginxrole      
