---
- name: creating_file
  file:
    path: /var/log/nginx/{{ username }}
    state: directory
- name: hosts_config
  lineinfile:
    path: /etc/hosts
    line: 13.126.30.46  sandy.opstree.com
    create: yes
- name: copying_file
  template:
    src: conf.j2
    dest: /etc/nginx/sites-available/{{ username }}.conf
- name: linking
  file:
   src: /etc/nginx/sites-available/{{ username }}.conf
   dest: /etc/nginx/sites-enabled/{{ username }}.conf
   state: link
- name: html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
- name: restart
  service:
    name: nginx
    state: restarted
