---
- hosts: webserver1 
  tasks:
   - name: checking if file exists
     stat:
       path: /var/www/html/index.nginx-debian.html
     register: stat_result
   - name: installing_nginx
     apt:
       name: nginx
       state: latest
     when: stat_result.stat.exits == False


