---
- hosts: webserver1
  become: true
  tasks:
  - name: installing_nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
  - name: starting_nginx
    service:
      name: nginx
      state: started
  - name: stopping_nginx
    service:
      name: nginx
      state: stopped
  - name: nginx_default_page
    lineinfile: 
      path: /var/www/html/index.nginx-debian.html 
      line: Hello! This is ninja Prajul 
      create: yes
  - name: restarting_nginx
    service:
      name: nginx
      state: restarted

