---
 - name: playbook to print environment variable
   hosts: all
   become: yes
   gather_facts: true
   tasks:
      - name: making html file in remote machine with env variable
        template: 
           src: index.html.j2
           dest: /tmp/index.html